server:
  port: 8088

spring:
  #配置数据源
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/udid?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: yibian123

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql


  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

  thymeleaf:
    cache: false
  resources:
    chain:
      s
#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 6个小时
  expiration: 21000000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

# 文件存储路径
file:
  path: D:\lala\
  avatar: D:\lala\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
